### ISSUE TITLE
✨ [Feature] 체력 및 소지품 UI 추가 및 버그 수정

### ISSUE THREAD

**Issue by Dorae0** [Chat-niverse/Chat-niverse_FE#10]
### Description

체력 및 소지품을 표현하는 UI를 추가합니다.
Choices가 들어오지 않는 경우 이미지 및 텍스트까지 같이 표시되지 않는 버그를 수정합니다.

### Todo

- [x] 체력 UI 추가
- [x] 소지품 UI 추가
- [x] Choices 0개일 경우 이미지 및 텍스트 표시하도록 수정
