### ISSUE TITLE
✨ [Feature] Main 화면 구현

### ISSUE THREAD

**Issue by Dorae0** [Chat-niverse/Chat-niverse_FE#4]
### Description

이미지, 설명 텍스트 및 선택지가 들어갈 화면을 구현합니다.
필요한 라이브러리들을 설치합니다.

### Todo

- [x] AI로 생성된 이미지를 화면에 출력
- [x] 설명 텍스트를 화면에 출력
- [x] 선택지들을 화면에 출력 (동적 출력 가능)

- [x] React-Responsive 설치 (반응형 웹)
`npm install react-responsive --save`
- [x] Axios 설치 (API 통신)
`npm install axios`
