### ISSUE TITLE
✨ [Feature] 초기 설정 화면 제작

### ISSUE THREAD

**Issue by Dorae0** [Chat-niverse/Chat-niverse_FE#6]
### Description

초기 설정 화면을 제작합니다.
유저의 세계관, 성격, 목표 등을 string으로 입력받습니다.
이후에 Axios 통신을 통하여 BE 또는 AI API에서 받아오는 데 사용됩니다.

### Todo

- [x] 초기 페이지 구현 (별개의 페이지로 할지, State로 받아서 할지)
    - [x] 유저의 이름 Form 
    - [x] 유저의 세계관 Form
    - [x] 유저의 성격 Form
    - [x] 유저의 목표 Form
    - [x] Submit Button
    - [x] FormData 내부 변수명 및 초기값 설정
